sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

# Defaults for edit
sonata_admin:
#    form_theme:
#        - '@FMElfinder/Form/elfinder_widget.html.twig'

    assets:
        stylesheets:
            # The default stylesheet list:
            - bundles/sonataadmin/app.css
        # stylesheet paths to add to the page in addition to the list above
        extra_stylesheets: ['bundles/sonatatranslation/css/sonata-translation.css']
        # stylesheet paths to remove from the page
        remove_stylesheets: []
        javascripts:
            # The default javascript list:
            - bundles/sonataadmin/app.js
        # javascript paths to add to the page in addition to the list above
        extra_javascripts: []
        # javascript paths to remove from the page
        remove_javascripts: []
    global_search:
        empty_boxes: show
        admin_route: show

    security:
        handler: sonata.admin.security.handler.noop
        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
        admin_permissions:
            # Defaults:
            - CREATE
            - LIST
            - DELETE
            - UNDELETE
            - EXPORT
            - OPERATOR
            - MASTER
        object_permissions:
            # Defaults:
            - VIEW
            - EDIT
            - HISTORY
            - DELETE
            - UNDELETE
            - OPERATOR
            - MASTER
            - OWNER
        acl_user_manager: null
    title: 'Deep Sleep'
    title_logo: favicon.ico
    search: true
    default_controller: 'sonata.admin.controller.crud'
    templates:
        user_block: '@SonataAdmin/Core/user_block.html.twig'
        add_block: '@SonataAdmin/Core/add_block.html.twig'
        layout: '@SonataAdmin/standard_layout.html.twig'
        ajax: '@SonataAdmin/ajax_layout.html.twig'
        dashboard: '@SonataAdmin/Core/dashboard.html.twig'
        search: '@SonataAdmin/Core/search.html.twig'
        list: '@SonataAdmin/CRUD/list.html.twig'
        filter: '@SonataAdmin/Form/filter_admin_fields.html.twig'
        show: '@SonataAdmin/CRUD/show.html.twig'
        show_compare: '@SonataAdmin/CRUD/show_compare.html.twig'
        edit: '@SonataAdmin/CRUD/edit.html.twig'
        preview: '@SonataAdmin/CRUD/preview.html.twig'
        history: '@SonataAdmin/CRUD/history.html.twig'
        acl: '@SonataAdmin/CRUD/acl.html.twig'
        history_revision_timestamp: '@SonataAdmin/CRUD/history_revision_timestamp.html.twig'
        action: '@SonataAdmin/CRUD/action.html.twig'
        select: '@SonataAdmin/CRUD/list__select.html.twig'
        list_block: '@SonataAdmin/Block/block_admin_list.html.twig'
        search_result_block: '@SonataAdmin/Block/block_search_result.html.twig'
        short_object_description: '@SonataAdmin/Helper/short-object-description.html.twig'
        delete: '@SonataAdmin/CRUD/delete.html.twig'
        batch: '@SonataAdmin/CRUD/list__batch.html.twig'
        batch_confirmation: '@SonataAdmin/CRUD/batch_confirmation.html.twig'
        inner_list_row: '@SonataAdmin/CRUD/list_inner_row.html.twig'
        outer_list_rows_mosaic: '@SonataAdmin/CRUD/list_outer_rows_mosaic.html.twig'
        outer_list_rows_list: '@SonataAdmin/CRUD/list_outer_rows_list.html.twig'
        outer_list_rows_tree: '@SonataAdmin/CRUD/list_outer_rows_tree.html.twig'
        base_list_field: '@SonataAdmin/CRUD/base_list_field.html.twig'
        pager_links: '@SonataAdmin/Pager/links.html.twig'
        pager_results: '@SonataAdmin/Pager/results.html.twig'
        tab_menu_template: '@SonataAdmin/Core/tab_menu_template.html.twig'
        knp_menu_template: '@SonataAdmin/Menu/sonata_menu.html.twig'
        form_theme: []
        filter_theme: []


