twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - 'form/elfinder_designed.html.twig'
    paths:
        'templates/website': 'web'
        'templates/email': 'email'
        'templates/bundles': 'bundle'
when@test:
    twig:
        strict_variables: true
