<?php

namespace ContainerUQpgWcy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonataTranslation_Listener_TranslatableService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata_translation.listener.translatable' shared service.
     *
     * @return \Gedmo\Translatable\TranslatableListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sonata_translation.listener.translatable'] = $instance = new \Gedmo\Translatable\TranslatableListener();

        $instance->setAnnotationReader(($container->privates['annotations.cached_reader'] ?? $container->getAnnotations_CachedReaderService()));
        $instance->setDefaultLocale('en');
        $instance->setTranslatableLocale('en');
        $instance->setTranslationFallback(false);

        return $instance;
    }
}
