<?php

namespace ContainerUQpgWcy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonataTranslation_Block_LocaleSwitcherService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sonata_translation.block.locale_switcher' shared service.
     *
     * @return \Sonata\TranslationBundle\Block\LocaleSwitcherBlockService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'sonata-project'.\DIRECTORY_SEPARATOR.'block-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Block'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'BlockServiceInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'sonata-project'.\DIRECTORY_SEPARATOR.'block-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Block'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'AbstractBlockService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'sonata-project'.\DIRECTORY_SEPARATOR.'translation-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Block'.\DIRECTORY_SEPARATOR.'LocaleSwitcherBlockService.php';

        $a = ($container->privates['twig'] ?? $container->getTwigService());

        if (isset($container->services['sonata_translation.block.locale_switcher'])) {
            return $container->services['sonata_translation.block.locale_switcher'];
        }

        return $container->services['sonata_translation.block.locale_switcher'] = new \Sonata\TranslationBundle\Block\LocaleSwitcherBlockService($a, ($container->privates['sonata_translation.admin.provider.request_locale_provider'] ?? $container->load('getSonataTranslation_Admin_Provider_RequestLocaleProviderService')));
    }
}
