<?php

namespace ContainerUQpgWcy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_MenuBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.admin.menu_builder' shared service.
     *
     * @return \Sonata\AdminBundle\Menu\MenuBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'sonata-project'.\DIRECTORY_SEPARATOR.'admin-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Menu'.\DIRECTORY_SEPARATOR.'MenuBuilder.php';

        $a = ($container->privates['sonata.admin.pool'] ?? $container->getSonata_Admin_PoolService());

        if (isset($container->privates['sonata.admin.menu_builder'])) {
            return $container->privates['sonata.admin.menu_builder'];
        }
        $b = ($container->services['knp_menu.factory'] ?? $container->load('getKnpMenu_FactoryService'));

        if (isset($container->privates['sonata.admin.menu_builder'])) {
            return $container->privates['sonata.admin.menu_builder'];
        }
        $c = ($container->privates['knp_menu.menu_provider.chain'] ?? $container->getKnpMenu_MenuProvider_ChainService());

        if (isset($container->privates['sonata.admin.menu_builder'])) {
            return $container->privates['sonata.admin.menu_builder'];
        }
        $d = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->privates['sonata.admin.menu_builder'])) {
            return $container->privates['sonata.admin.menu_builder'];
        }

        return $container->privates['sonata.admin.menu_builder'] = new \Sonata\AdminBundle\Menu\MenuBuilder($a, $b, $c, $d);
    }
}
