<?php

namespace ContainerUQpgWcy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonataTranslation_Admin_Extension_GedmoTranslatableService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata_translation.admin.extension.gedmo_translatable' shared service.
     *
     * @return \Sonata\TranslationBundle\Admin\Extension\Gedmo\TranslatableAdminExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'sonata-project'.\DIRECTORY_SEPARATOR.'admin-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Admin'.\DIRECTORY_SEPARATOR.'AdminExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'sonata-project'.\DIRECTORY_SEPARATOR.'admin-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Admin'.\DIRECTORY_SEPARATOR.'AbstractAdminExtension.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'sonata-project'.\DIRECTORY_SEPARATOR.'translation-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Admin'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'AbstractTranslatableAdminExtension.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'sonata-project'.\DIRECTORY_SEPARATOR.'translation-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Admin'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'Gedmo'.\DIRECTORY_SEPARATOR.'TranslatableAdminExtension.php';

        return $container->privates['sonata_translation.admin.extension.gedmo_translatable'] = new \Sonata\TranslationBundle\Admin\Extension\Gedmo\TranslatableAdminExtension(($container->privates['sonata_translation.checker.translatable'] ?? $container->getSonataTranslation_Checker_TranslatableService()), ($container->privates['sonata_translation.listener.translatable'] ?? $container->load('getSonataTranslation_Listener_TranslatableService')), ($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->privates['sonata_translation.admin.provider.request_locale_provider'] ?? $container->load('getSonataTranslation_Admin_Provider_RequestLocaleProviderService')));
    }
}
